parameters:
#    movimiento.example.class: SPV\MovimientoBundle\Example

services:
#    movimiento.example:
#        class: %movimiento.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
