usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

producto:
    resource: "@ProductoBundle/Resources/config/routing.yml"
    prefix:   /

direccion:
    resource: "@DireccionBundle/Resources/config/routing.yml"
    prefix:   /

movimiento:
    resource: "@MovimientoBundle/Resources/config/routing.yml"
    prefix:   /

cliente:
    resource: "@ClienteBundle/Resources/config/routing.yml"
    prefix:   /cliente

proveedor:
    resource: "@ProveedorBundle/Resources/config/routing.yml"
    prefix:   /

portada:
    pattern: /
    defaults: { _controller: ProductoBundle:Default:portada }

productos:
    pattern: /productos
    defaults: { _controller: ProductoBundle:Default:productos }

detalle:
    pattern: /detalle
    defaults: { _controller: ProductoBundle:Default:detalleproducto }

error:
    pattern: /error404
    defaults: { _controller: ProductoBundle:Default:error }

contacto:
    pattern: /contacto
    defaults: { _controller: ProductoBundle:Default:contacto }

adios:
    pattern: /adios
    defaults: { _controller: ProductoBundle:Default:adios }