usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /admin

producto:
    resource: "@ProductoBundle/Resources/config/routing.yml"
    prefix:   /admin

direccion:
    resource: "@DireccionBundle/Resources/config/routing.yml"
    prefix:   /

movimiento:
    resource: "@MovimientoBundle/Resources/config/routing.yml"
    prefix:   /admin

cliente:
    resource: "@ClienteBundle/Resources/config/routing.yml"
    prefix:   /cliente

proveedor:
    resource: "@ProveedorBundle/Resources/config/routing.yml"
    prefix:   /admin

portada:
    pattern: /
    defaults: { _controller: ProductoBundle:Default:portada }

productos:
    pattern: /productos/{categoria}
    defaults: { _controller: ProductoBundle:Default:productos, categoria: 'todos'}

detalle:
    pattern: /detalle/{id}
    defaults: { _controller: ProductoBundle:Default:detalleproducto }

error:
    pattern: /error404
    defaults: { _controller: ProductoBundle:Default:error }

contacto:
    pattern: /contacto
    defaults: { _controller: ProductoBundle:Default:contacto }

adios:
    pattern: /adios
    defaults: { _controller: ProductoBundle:Default:adios }

