security:
    firewalls:
        publico:
            pattern: ^/*
            anonymous: ~
            form_login:
                login_path: cliente_login
                check_path: cliente_login_check
    access_control:
        - { path: ^/cliente/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cliente/*, roles: ROLE_CLIENTE }
    providers:
        cliente:
            entity: { class: SPV\ClienteBundle\Entity\Cliente, property: email }
    encoders:
        SPV\ClienteBundle\Entity\Cliente: plaintext