parameters:
#    direccion.example.class: SPV\DireccionBundle\Example

services:
#    direccion.example:
#        class: %direccion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
