<?php

namespace SPV\ProductoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends EntityRepository
{
    public function findRecientes(){
        $em=$this->getEntityManager();
        $consulta=$em->createQuery('
        SELECT p
        FROM ProductoBundle:Producto p
        WHERE p.fechaIngreso BETWEEN :hoy AND :final
        ORDER BY p.fechaIngreso DESC');
        $consulta->setMaxResults(6);
        $consulta->setParameter('hoy',new \DateTime('today'));
        $consulta->setParameter('final',new \DateTime('today + 7 days'));

        return $consulta->getResult();
    }
    public function findPopulares(){
        $em=$this->getEntityManager();
        $consulta=$em->createQuery('
        SELECT p
        FROM ProductoBundle:Producto p
        ORDER BY p.ranking DESC');
        $consulta->setMaxResults(6);

        return $consulta->getResult();
    }
}
