<?php

namespace SPV\ClienteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarritoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarritoRepository extends EntityRepository
{
	public function findProductos($id){
        $em=$this->getEntityManager();
        $consulta=$em->createQuery('
            SELECT c, p
            FROM ClienteBundle:Carrito c
            JOIN c.producto p
            WHERE c.fechaAdd = :fecha AND c.cliente.id = :cliente');
        $consulta->setParameter('cliente', $id);
        $consulta->setParameter('fecha', new \DateTime('today'));

        return $consulta->getResult();
    }
}
