<?php

namespace SPV\DireccionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConfGralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfGralRepository extends EntityRepository
{
}
