<?php

namespace SPV\DireccionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Class DireccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DireccionRepository extends EntityRepository
{

}