<?php

namespace SPV\DireccionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FechaPedidosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FechaPedidosRepository extends EntityRepository
{
}
