BackendUsuario:
    resource: "@UsuarioBundle/Resources/config/routing/usuario.yml"
    prefix: /usuarios

admin:
    pattern: /
    defaults: { _controller: UsuarioBundle:Admin:principal }

usuario_login:
    pattern: /login
    defaults: { _controller: UsuarioBundle:Admin:login }

usuario_login_check:
    pattern: /login_check

usuario_logout:
    pattern: /logout
