usuario_registro:
    pattern:  /registro
    defaults: { _controller: UsuarioBundle:Admin:registro }

admin:
    pattern: /
    defaults: { _controller: UsuarioBundle:Admin:prueba }

usuario_login:
    pattern: /login
    defaults: { _controller: UsuarioBundle:Admin:login }

usuario_login_check:
    pattern: /login_check

usuario_logout:
    pattern: /logout
