<?php

namespace SPV\MovimientoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DetalleMovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleMovimientoRepository extends EntityRepository
{
}
