proveedor_registro:
    pattern:  /registro-proveedor
    defaults: { _controller: ProveedorBundle:Admin:registro }

lista_proveedores:
    pattern: /lista-proveedores
    defaults: { _controller: ProveedorBundle:Admin:lista }

editar_proveedor:
    pattern: /editar-provedor/{id}
    defaults: { _controller: ProveedorBundle:Admin:editar }
