pedido:
    pattern: /pedido/
    defaults: { _controller: ClienteBundle:Default:pedido }

perfil:
    pattern: /perfil/
    defaults: { _controller: ClienteBundle:Default:perfil }

cliente_login:
    pattern:  /login
    defaults: { _controller: ClienteBundle:Default:login }

cliente_login_check:
    pattern: /login_check

cliente_logout:
    pattern: /logout

cliente_regsitro:
    pattern: /registrate/
    defaults: { _controller: ClienteBundle:Default:registro }

modificar_cliente:
    pattern: /modificar-informacion/
    defaults: { _controller: ClienteBundle:Default:editar }

sylius_cart:
    resource: @SyliusCartBundle/Resources/config/routing.yml
    prefix: /carrito

confirmar_pedido:
   pattern: /confirmar-pedido/
   defaults: { _controller: ClienteBundle:Default:nuevoPedido }