parameters:
#    cliente.example.class: SPV\ClienteBundle\Example

services:
    # login_listener:
    #     class: SPV\ClienteBundle\Listener\LoginListener
    #     arguments: [@router]
    #     tags:
    #         - { name: kernel.event_listener, event: security.interactive_login }
    #         - { name: kernel.event_listener, event: kernel.response }
    app.cart_item_resolver:
        class: SPV\ClienteBundle\Cart\ItemResolver
        arguments: [doctine.orm.entity_manager]