colonia:
    path:     /
    defaults: { _controller: "BackendBundle:Colonia:index" }

colonia_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Colonia:new" }

colonia_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Colonia:create" }
    requirements: { _method: post }

colonia_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Colonia:edit" }

colonia_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Colonia:update" }
    requirements: { _method: post|put }

colonia_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Colonia:delete" }
    requirements: { _method: get|delete }
